- Gemfile
- Gemfile.lock
- config/database.yml
- db/schema.rb
> Changedatabase

- .vscode/settings.json
- app/controllers/application_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- db/migrate/20210510104945_add_signup_columns.rb
- db/schema.rb
1. 新增註冊頁面欄位，並將性別設為索引，日後若需要統計數據可用
2. 可編輯部分欄位（電話、信箱、銀行帳戶）
3. 資料可寫入資料庫內
4. 修改帳戶編輯頁面的back，路徑為回到首頁
> Signup_columns

- app/javascript/packs/application.js
- app/javascript/styles/index.js
- app/javascript/styles/tailwind.scss
- app/javascript/stylesheets/application.scss
- app/javascript/stylesheets/components/buttons.scss
- app/javascript/stylesheets/components/forms.scss
- app/javascript/stylesheets/tailwind.config.js
- app/views/devise/sessions/new.html.erb
- postcss.config.js
修改tailwind輸出資料夾配置
修改路徑users/sign_in的form樣式
> 修改sign_in頁面樣式

- app/models/task.rb
- app/views/tasks/_form.html.erb
- app/views/tasks/index.html.erb
- config/initializers/time_formats.rb
- config/locales/zh-TW.yml
> Task table list validates

- app/javascript/stylesheets/tailwind.config.js
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
1.新增tailwind.config.js的purge路徑
2.修改sing_in跟forgot password頁面
> Login view

- app/models/user.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- db/schema.rb
1. 增加註冊欄位驗證（電話至少10碼、信用卡長度、其餘不可空白）
2. 刪除重複的欄位
> Signup validates

- app/controllers/tasks_controller.rb
- app/helpers/tasks_helper.rb
- app/mailers/user_mailer.rb
- app/models/task.rb
- app/views/user_mailer/someone_apply_note.html.erb
- app/views/user_mailer/someone_apply_note.text.erb
- db/migrate/20210511094830_add_state_to_tasks.rb
- db/schema.rb
- spec/fixtures/user/someone_apply_note
- spec/mailers/previews/user_preview.rb
- spec/mailers/user_spec.rb
1. 創立 mailer scaffold
2. 增加 state column 於 task
3. 增加方法以在有人申請應徵 task 時，寄信通知 employer
> Employer get mail after employee apply

- app/views/tasks/new.html.erb
> fix navbar posiotion

- app/helpers/tasks_helper.rb
- app/models/order.rb
- app/models/task.rb
- app/views/shared/_header.html.erb
- app/views/tasks/index.html.erb
- db/migrate/20210512094215_create_orders.rb
- spec/factories/orders.rb
- spec/models/order_spec.rb
> Fix task list with states and authors

- app/controllers/users/omniauth_callbacks_controller.rb
- app/controllers/users/registrations_controller.rb
- app/models/user.rb
1. 修正註冊欄位清洗資料的方式，本來放在applications_controller底下，移到user/registrations_controller
2. 刪除user model的驗證，因使用第三方登入無銀行帳號、電話號碼，此驗證需重新設置
> <Fix> registrations_columns

- app/views/devise/registrations/edit.html.erb
- app/views/lists/index.html.erb
- app/views/shared/_footer.html.erb
- app/views/tasks/show.html.erb
修正footer路徑
views/tasks/show.html.erb
刪除影響第三方登入資訊
> Hot fix 0520

- config/routes.rb
> sort out routes

- app/models/task.rb
> fix:Task model

- app/views/tasks/finish_show.html.erb
- app/views/tasks/show.html.erb
> qrode icon

- app/controllers/tasks_controller.rb
- app/views/tasks/error.html.erb
- app/views/tasks/finish.html.erb
- app/views/tasks/finish_show.html.erb
- app/views/tasks/show.html.erb
> qrcode-finish_show/error/finish

- app/javascript/view-event/task_new_validate.js
- app/views/tasks/_form.html.erb
1.修正task_new_validate.js檔造成console噴錯問題
2.修正新增任務的酬勞欄位跑版問題
> 修正task_new_validate.js檔造成console噴錯問題

- app/javascript/stylesheets/page/task-all.scss
- app/views/tasks/_tasks_bar.html.erb
1.讓sidebar不要被任務卡片蓋住
2.使點擊icon也能跳轉頁面
> fix sidebar-icon and z-index

- app/javascript/stylesheets/page/task-all.scss
- app/views/tasks/_index.html.erb
- app/views/tasks/_tasks_bar.html.erb
- app/views/tasks/show.html.erb
1.修正詳細任務頁地圖與按鈕跑版
2.改寫link_to寫法
> fix task_show's map and button position

- app/javascript/controllers/map_controller.js
- config/environments/development.rb
> Customize marker image

- app/channels/room_channel.rb
- app/controllers/messages_controller.rb
- app/controllers/rooms_controller.rb
- app/javascript/controllers/chat_controller.js
- app/jobs/send_message_job.rb
- app/views/messages/_form.html.erb
- app/views/rooms/show.html.erb
- config/routes.rb
忘了issue#226 assignee自己 
但效果沒有很好 票我會關。怕再接的只注重"外觀"。
沒有寫code。
> Feat#chat add event

- app/javascript/packs/qrcode.js
> fix qrcode repeat const

- app/javascript/packs/qrcode.js
> 更改qrcode變數

- config/application.rb
- lib/cloudflare_proxy.rb
修正購買的網域 rowleg.online 問題，讓其可正常操作！
> fix: cloudflare http match bug

- app/javascript/controllers/map_controller.js
- app/javascript/stylesheets/components/buttons.scss
- app/javascript/stylesheets/layout/header.scss
- app/javascript/stylesheets/page/task-show.scss
- app/javascript/stylesheets/tailwind.config.js
- app/views/tasks/show.html.erb
> Task-show RWD and change hamburger design

- app/javascript/controllers/map_controller.js
- app/javascript/stylesheets/components/buttons.scss
- app/javascript/stylesheets/page/task-show.scss
- app/javascript/view-event/task_all.js
- app/views/tasks/_index.html.erb
- app/views/tasks/show.html.erb
1.增加讓跑腿員可選交通手段後回報
2.移除舊的任務狀態欄跟多餘註解
> Add travel mode option

- app/controllers/home_controller.rb
- app/controllers/users/registrations_controller.rb
- app/javascript/scripts/validations/form_validate.js
- app/models/user.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- db/migrate/20210602145941_remove_columns_from_users.rb
- db/schema.rb
- 有新增migration刪除 age 和 gender 的欄位
- 合併後記得要執行 `db:migrate`
> refactor : signup_column & validation 

- app/javascript/controllers/chat_controller.js
- app/javascript/scripts/message.js
- app/views/rooms/show.html.erb
> Refactor#message.js

- Gemfile
- Gemfile.lock
- app/controllers/tasks_controller.rb
- app/models/task.rb
- config/environments/development.rb
請記得bundle 加了一個開發環境的gem Bullet
提示有沒有N+1 用
聊天室的還沒處理。出現下面圖示很正常
> 處理任務列首頁資料N+1
